### ISSUE TITLE
Transitions not running asynchronously

### ISSUE THREAD

**Issue by buzztiaan** [jnimmo/hass-dmx#6]
Heya, i have RGB lamps that have 10 'lights' and 3 channels per light. 

I would like to control all these lights at once :)

**Comment by buzztiaan** [comment]
My mates told my to bundle all channels in a group to get a 'group switch' to turn em on/off at least.

Weirdly, that then causes it to fade each seperate channel after each other, not really useful :D

**Comment by buzztiaan** [comment]
Welp, and that also lacks the ability to send 1 RGB value to all channels

**Comment by buzztiaan** [comment]
I think what i really want is some method to 'bundle' multiple light entities into 1 , that controls them all simultaneous  
Also would be nice to bundle multiple of those into one through the same methodology

**Comment by buzztiaan** [comment]
'Transition' to zero on all, and just normal groups will have to do for now ;)

**Comment by jnimmo** [comment]
Thanks for your feedback and trying it out!
Bundling lights will be out of scope for this project, this should be done with Home Assistant groups or by setting the same DMX channel on all of the fixtures.
But - the groups should control them all simultaneously rather than one after the other. I'll concentrate on getting that resolved, the code must not be running asynchronously. Will let you know when there is something to test

**Comment by jnimmo** [comment]
Hey @buzztiaan, @sgoudsme has fixed this and I've finally got around to testing. Can you see if it is sorted now?
